"""
UE Python Startup Script Example

This is an example file. The actual startup script is automatically 
deployed to your UE project's Content/Python directory by the 
DCC Tool Manager.

To enable auto-start:
1. Open DCC Tool Manager UI
2. Select "Unreal Engine" from DCC dropdown
3. Click "Settings" button
4. Click "Auto-configure" and select your UE project path

The tool will:
- Copy ue_script_listener.py to [UE_Project]/Content/Python/
- Create or update init_unreal.py with startup code
- Restart UE to activate
"""

# This file is for reference only
# The actual startup code is generated by the DCC Tool Manager